spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:172.16.17.37:8848}
  application:
    name: ts-config-service
  datasource:
    url: jdbc:mysql://${CONFIG_MYSQL_HOST:172.16.17.38}:${CONFIG_MYSQL_PORT:3306}/${CONFIG_MYSQL_DATABASE:ts_config_mysql}?useSSL=false
    username: ${CONFIG_MYSQL_USER:root}
    password: ${CONFIG_MYSQL_PASSWORD:passwordA123$}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


# HTTP Server
server:
  port: 15679  # HTTP (Tomcat) port

swagger:
  controllerPackage: config.controller