server:
  port: 18957

spring:
  cloud:
    nacos:
      discovery:
          server-addr: ${NACOS_ADDRS:172.16.17.37:8848}
#          server-addr: 10.176.122.80:8848
  application:
    name: ts-food-delivery-service
  datasource:
#    url: jdbc:mysql://localhost:30001/ts-food-delivery-mysql?useSSL=false
    url: jdbc:mysql://${FOOD_DELIVERY_MYSQL_HOST:172.16.17.38}:${FOOD_DELIVERY_MYSQL_PORT:3306}/${FOOD_DELIVERY_MYSQL_DATABASE:ts_food_mysql}?useSSL=false
    username: ${FOOD_DELIVERY_MYSQL_USER:root}
    password: ${FOOD_DELIVERY_MYSQL_PASSWORD:passwordA123$}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

swagger:
  controllerPackage: fooddelivery.controller