spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:172.16.17.37:8848}
  application:
    name: ts-price-service
  datasource:
    url: jdbc:mysql://${PRICE_MYSQL_HOST:172.16.17.38}:${PRICE_MYSQL_PORT:3306}/${PRICE_MYSQL_DATABASE:ts}?useSSL=false
    username: ${PRICE_MYSQL_USER:root}
    password: ${PRICE_MYSQL_PASSWORD:passwordA123$}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


# HTTP Server
server:
  port: 16579  # HTTP (Tomcat) port

swagger:
  controllerPackage: price.controller