server:
  port: 18855

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:172.16.17.37:8848}
  application:
    name: ts-station-food-service
  datasource:
#    url: jdbc:mysql://localhost:3306/ts-station-food-mysql?useSSL=false
    url: jdbc:mysql://${STATION_FOOD_MYSQL_HOST:172.16.17.38}:${STATION_FOOD_MYSQL_PORT:3306}/${STATION_FOOD_MYSQL_DATABASE:ts}?useSSL=false
    username: ${STATION_FOOD_MYSQL_USER:root}
    password: ${STATION_FOOD_MYSQL_PASSWORD:passwordA123$}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

swagger:
  controllerPackage: food.controller